# Generated by Django 3.1.7 on 2021-03-29 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('rue', models.CharField(max_length=100)),
                ('codepostal', models.DecimalField(decimal_places=0, max_digits=5)),
                ('ville', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Catprofessionnelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('datenaissance', models.DateField()),
                ('ntel', models.DecimalField(decimal_places=0, max_digits=10)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('catcommerciale', models.CharField(choices=[('PROSPECT', 'possible client'), ('CLIENT', 'client'), ('INTERDIT', ' client interdit')], default='PROSPECT', max_length=20)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referentiel.adresse')),
                ('catprofessionnelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referentiel.catprofessionnelle')),
            ],
        ),
    ]
