# Generated by Django 3.1.7 on 2021-03-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0002_auto_20210313_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcommerciale',
            name='nom',
            field=models.CharField(choices=[('PROSPECT', 'possible client'), ('CLIENT', 'client'), ('INTERDIT', ' client interdit')], default='PROSPECT', max_length=20),
        ),
    ]
