# Generated by Django 3.1.7 on 2021-03-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'permissions': [('perm_administrerRef', 'peut acceder a la vue administration referentiel'), ('perm_publicite', 'peut acceder a la vue publicite'), ('perm_commandes', 'peut acceder a la vue commandes')]},
        ),
    ]
