# Generated by Django 3.1.7 on 2021-04-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_auto_20210329_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'permissions': [('perm_administrerRef', 'peut acceder a la vue administration referentiel'), ('perm_publicite', 'peut acceder a la vue publicite'), ('perm_commandes', 'peut acceder a la vue commandes'), ('perm_anomalies', 'peut acceder a la vue anomalies')]},
        ),
    ]
