# Generated by Django 3.1.7 on 2021-03-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('dateenvoi', models.DateTimeField()),
                ('format', models.CharField(choices=[('PST', 'format papier standard'), ('PEC', 'format papier econimique'), ('PSU', 'format papier superieur'), ('INT', 'format internet')], default='PST', max_length=3)),
                ('articles', models.ManyToManyField(to='referentiel.Article')),
                ('individus', models.ManyToManyField(to='referentiel.Individu')),
            ],
        ),
    ]
