# Generated by Django 3.1.7 on 2021-03-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
        ('publicite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicite',
            name='articles',
            field=models.ManyToManyField(max_length=5, to='referentiel.Article'),
        ),
    ]
