# Generated by Django 3.1.7 on 2021-03-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
        ('publicite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicite',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='publicite',
            name='individus',
        ),
        migrations.CreateModel(
            name='Cible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valide', models.BooleanField(default=False)),
                ('individus', models.ManyToManyField(to='referentiel.Individu')),
            ],
        ),
        migrations.AddField(
            model_name='publicite',
            name='cible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publicite.cible'),
            preserve_default=False,
        ),
    ]
