# Generated by Django 3.1.7 on 2021-03-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
        ('publicite', '0002_publicite_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicite',
            name='articles',
            field=models.ManyToManyField(to='referentiel.Article'),
        ),
    ]
