# Generated by Django 3.1.7 on 2021-03-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicite', '0003_auto_20210327_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicite',
            name='dateenvoi',
            field=models.DateTimeField(null=True),
        ),
    ]
